052223-java-angular/Pawel-Sebastian-p0

.gitignore
pom.xml
src/main/java/com/revature/ecommerce_cli/App.java
src/test/java/com/revature/ecommerce_cli/AppTest.java

closes #1 
Also change directory names to more appropriate values, create folders for resources & db (sql)

Dependencies setup

---

.gitignore
pom.xml
src/main/java/com/mycompany/app/App.java
src/test/java/com/mycompany/app/AppTest.java

Reverts 052223-java-angular/Pawel-Sebastian-p0#15

Revert "Dependencies setup"

---

src/main/resources/db/ddl.sql

add file for Data Definition. Later, write methods to load it into some database for testing as well as connection code.

add ddl.sql

---

src/main/java/com/revature/ecommerce_cli/Util/ConnectionFactory.java
src/main/resources/db/ddl.sql
src/test/java/com/revature/ecommerce_cli/DBTest.java

add connection using ConnectionFactory, fix ddl.sql, add test for running db connection.

Jdbc initial

---

pom.xml
src/main/java/com/revature/ecommerce_cli/models/CartProducts.java
src/main/java/com/revature/ecommerce_cli/models/OrderProducts.java
src/main/java/com/revature/ecommerce_cli/models/Orders.java
src/main/java/com/revature/ecommerce_cli/models/PaymentMethods.java
src/main/java/com/revature/ecommerce_cli/models/Products.java
src/main/java/com/revature/ecommerce_cli/models/Reviews.java
src/main/java/com/revature/ecommerce_cli/models/Users.java

added models and lombok dependency

added models and lombok dep

---

src/main/java/com/revature/ecommerce_cli/App.java
src/main/java/com/revature/ecommerce_cli/screens/HomeScreen.java
src/main/java/com/revature/ecommerce_cli/screens/IScreen.java
src/main/java/com/revature/ecommerce_cli/screens/RegisterScreen.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java
src/main/java/com/revature/ecommerce_cli/services/UserService.java

added home, i and register screens
added router and userservice, need to complete userservice validation implementation

added screens and services for registration

---

src/main/java/com/revature/ecommerce_cli/DAO/CartProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ReviewDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/UserDAO.java
src/main/java/com/revature/ecommerce_cli/Models/CartProduct.java
src/main/java/com/revature/ecommerce_cli/Models/Order.java
src/main/java/com/revature/ecommerce_cli/Models/OrderProduct.java
src/main/java/com/revature/ecommerce_cli/Models/PaymentMethod.java
src/main/java/com/revature/ecommerce_cli/Models/Product.java
src/main/java/com/revature/ecommerce_cli/Models/Review.java
src/main/java/com/revature/ecommerce_cli/Models/User.java
src/main/java/com/revature/ecommerce_cli/Util/ConnectionFactory.java
src/test/java/com/revature/ecommerce_cli/DBTest.java

Also add CartProductDAO and OrderProductDAO, fix some missing executeUpdate()s

make directory and field names consistent

---

src/main/java/com/revature/ecommerce_cli/DAO/CartProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ReviewDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/UserDAO.java

Fix Typos, add 'find by' functionality for DAOs

---

.gitignore
src/main/java/com/revature/ecommerce_cli/DAO/CartProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ReviewDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/UserDAO.java

Fix exceptions to give the correct info

fix DAO exceptions

---

src/main/java/com/revature/ecommerce_cli/screens/HomeScreen.java
src/main/java/com/revature/ecommerce_cli/screens/LoginScreen.java
src/main/java/com/revature/ecommerce_cli/screens/RegisterScreen.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java
src/main/java/com/revature/ecommerce_cli/services/UserService.java

-added login screen and login Userservice method

added basic login functionality

---

src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/models/Product.java
src/main/resources/db/ddl.sql

add in_stock to products table

---

src/main/java/com/revature/ecommerce_cli/DAO/CartProductDAO.java
src/main/java/com/revature/ecommerce_cli/DTO/CartItem.java
src/main/java/com/revature/ecommerce_cli/screens/HomeScreen.java
src/main/java/com/revature/ecommerce_cli/screens/LoginScreen.java
src/main/java/com/revature/ecommerce_cli/screens/MenuScreen.java
src/main/java/com/revature/ecommerce_cli/screens/RegisterScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ShoppingCartScreen.java
src/main/java/com/revature/ecommerce_cli/services/CartProductService.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java
src/main/java/com/revature/ecommerce_cli/util/PriceUtil.java
src/main/resources/db/ddl.sql

Initial shopping cart integration, still have to implement adding/browsing products, checkout, & payment.

Shopping cart

---

src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/models/Product.java
src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java
src/main/resources/db/ddl.sql
src/main/resources/db/dml_product.sql
src/main/resources/db/dml_testing.sql

Add product description

---

src/main/java/com/revature/ecommerce_cli/DAO/OrderDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DTO/OrderItem.java
src/main/java/com/revature/ecommerce_cli/screens/MenuScreen.java
src/main/java/com/revature/ecommerce_cli/screens/OrderHistoryScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ShoppingCartScreen.java
src/main/java/com/revature/ecommerce_cli/services/CartService.java
src/main/java/com/revature/ecommerce_cli/services/OrderHistoryService.java
src/main/java/com/revature/ecommerce_cli/services/ProductService.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java
src/main/java/com/revature/ecommerce_cli/util/PriceUtil.java
src/main/java/com/revature/ecommerce_cli/util/custom_exceptions/ProductNotFoundException.java

Order history

---

src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DTO/OrderItem.java
src/main/java/com/revature/ecommerce_cli/screens/OrderHistoryScreen.java

also better input/screen handling

Add Category to Order Items in order history

---

src/main/java/com/revature/ecommerce_cli/screens/ShoppingCartScreen.java

maybe later add a "Empty Shopping Cart" if there's time
Checkout/payment still needs to be done.
closes #5

Finish up Shopping cart

---

src/main/java/com/revature/ecommerce_cli/DAO/CartProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/OrderProductDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/ProductDAO.java
src/main/java/com/revature/ecommerce_cli/screens/OrderHistoryScreen.java
src/main/resources/db/dml_product.sql
src/main/resources/db/dml_testing.sql

Order query results

---

src/main/java/com/revature/ecommerce_cli/App.java
src/main/java/com/revature/ecommerce_cli/screens/HomeScreen.java
src/main/java/com/revature/ecommerce_cli/screens/LoginScreen.java
src/main/java/com/revature/ecommerce_cli/screens/MenuScreen.java
src/main/java/com/revature/ecommerce_cli/screens/OrderHistoryScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java
src/main/java/com/revature/ecommerce_cli/screens/RegisterScreen.java
src/main/resources/log4j2.xml

Set up logging and add it to most existing screens.
Should still be done for search screens.

Logging extra

---

src/main/java/com/revature/ecommerce_cli/screens/BrowsingScreen.java
src/main/java/com/revature/ecommerce_cli/screens/MenuScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ReviewScreen.java
src/main/java/com/revature/ecommerce_cli/screens/SearchingScreen.java
src/main/resources/db/ddl.sql

This makes menu handling better, handling "exit" and returning from previous pages visited, and adding "priceutil" displays for everything (I think)

Fix Formatting & menu exiting

---

src/main/java/com/revature/ecommerce_cli/DAO/ReviewDAO.java
src/main/java/com/revature/ecommerce_cli/DAO/UserDAO.java
src/main/java/com/revature/ecommerce_cli/screens/AddReviewScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java
src/main/java/com/revature/ecommerce_cli/services/ReviewService.java

Users can only leave 1 review per product; if a user tries to leave a review for a product that they've already reviewed they are prompted to overwrite it.

add single review per product per user

---

src/main/java/com/revature/ecommerce_cli/screens/AddReviewScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java
src/main/java/com/revature/ecommerce_cli/screens/ReviewScreen.java

Pull state of logging into develop

Logging for now

---

src/main/java/com/revature/ecommerce_cli/screens/CheckoutScreen.java
src/main/java/com/revature/ecommerce_cli/services/CartService.java
src/main/java/com/revature/ecommerce_cli/services/OrderService.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java

clearcart and stock validation

---

src/main/java/com/revature/ecommerce_cli/services/OrderService.java
src/main/java/com/revature/ecommerce_cli/services/RouterService.java

product in_stock decrement

---

src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java

cart quantity update

---

src/main/java/com/revature/ecommerce_cli/screens/ProductScreen.java

-added in stock info to add to cart

in stock info
